cloud:
  aws:
    region:
      static: ap-south-1
      auto: false
    stack:
      auto: false
    credentials:
      access-key: <Access-Key>
      secret-key: <Screet-Key>
    end-point:
      uri: https://sqs.ap-south-1.amazonaws.com/674768297865/SQS-queue


server:
  port: 8083
  
api:
  docNofiyUri: http://localhost:8083/test